# Form implementation generated from reading ui file 'c:\Users\Hao-Huawei\Desktop\project\camera\Camera-Collector\src\ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 689)
        MainWindow.setMinimumSize(QtCore.QSize(951, 689))
        MainWindow.setMaximumSize(QtCore.QSize(951, 689))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_pic = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pic.setMinimumSize(QtCore.QSize(640, 480))
        self.label_pic.setAutoFillBackground(True)
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.verticalLayout_5.addWidget(self.label_pic)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(49, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_ipPort = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_ipPort.setObjectName("lineEdit_ipPort")
        self.horizontalLayout.addWidget(self.lineEdit_ipPort)
        self.checkBox_camera = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox_camera.setObjectName("checkBox_camera")
        self.horizontalLayout.addWidget(self.checkBox_camera)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_cameraStatus = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_cameraStatus.setObjectName("label_cameraStatus")
        self.verticalLayout.addWidget(self.label_cameraStatus)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setEnabled(True)
        self.label_7.setMinimumSize(QtCore.QSize(49, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_filePath = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_filePath.setEnabled(False)
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.horizontalLayout_5.addWidget(self.lineEdit_filePath)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_filePath = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_filePath.setEnabled(False)
        self.pushButton_filePath.setObjectName("pushButton_filePath")
        self.horizontalLayout_6.addWidget(self.pushButton_filePath)
        self.pushButton_upgrade = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_upgrade.setEnabled(False)
        self.pushButton_upgrade.setObjectName("pushButton_upgrade")
        self.horizontalLayout_6.addWidget(self.pushButton_upgrade)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.checkBox_camera.released.connect(MainWindow.update) # type: ignore
        self.pushButton_filePath.released.connect(MainWindow.update) # type: ignore
        self.pushButton_upgrade.released.connect(MainWindow.update) # type: ignore
        self.lineEdit_filePath.textChanged['QString'].connect(MainWindow.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "摄像头采集器"))
        self.groupBox_2.setTitle(_translate("MainWindow", "WiFi"))
        self.label_4.setText(_translate("MainWindow", "摄像头："))
        self.lineEdit_ipPort.setText(_translate("MainWindow", "192.168.0.100:10000"))
        self.checkBox_camera.setText(_translate("MainWindow", "连接"))
        self.label_cameraStatus.setText(_translate("MainWindow", "摄像头未连接"))
        self.label_7.setText(_translate("MainWindow", "固件："))
        self.pushButton_filePath.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_upgrade.setText(_translate("MainWindow", "摄像头升级"))
