name: PyInstaller Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clean pyinstaller build folder
      run: |
        rm -rf build
        rm -rf dist

    - name: Build executable
      run: |
        pyinstaller pyinstaller-build.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Camera-Collector.exe
        path: dist/Camera-Collector.exe

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: Camera-Collector.exe
        token: ${{ secrets.GITHUB_TOKEN }}

